"""REAL Creative-Commons music corpus: download, decode, attribute.

This module is the bridge from the SYNTHETIC evaluation (:mod:`audio_fingerprint.synth`)
to **real recorded music**. It fetches a modest set of Creative-Commons-licensed
tracks from the Internet Archive ``netlabels`` collection, decodes them to mono
arrays at the pipeline's working sample rate, and records provenance and license
for every track so the corpus is fully attributable and reproducible.

Why the Internet Archive ``netlabels`` collection
-------------------------------------------------
It is large (tens of thousands of items), reliably reachable over plain HTTP, and
every item selected here carries an explicit ``creativecommons.org`` license URL —
the search query filters on ``licenseurl`` so nothing without a CC license is ever
downloaded. The audio is *real released music* (electronic, experimental, jazz,
hip-hop, ...), which is exactly the point: unlike the synthetic corpus, it has
vibrato, inharmonicity, real production chains, and — because tracks come from the
same netlabels and albums — genuinely confusable material, which is what stresses
the false-accept side of the evaluation.

What is and is not redistributed
--------------------------------
**No audio is committed to the repository.** Downloads are cached under ``data/``
(git-ignored). What the project commits is code, the measured results JSON, and
``DATA_SOURCES.md`` — a plain-text attribution table (title, creator, license,
Archive.org identifier) generated by :func:`write_data_sources`. Fingerprints and
indices are derived statistics, not the audio, and are also kept out of git. This
respects even the NonCommercial / NoDerivatives CC variants: the audio is used
locally for analysis and is attributed, never re-hosted.

Dependency isolation
--------------------
The network and heavy-audio dependencies (:mod:`librosa`, :mod:`soundfile`) are
imported **lazily inside functions**. Importing the core ``audio_fingerprint``
package therefore stays numpy/scipy-only, and the synthetic evaluation and CI
never touch the network or require the extra packages. Install them with the
optional extra: ``pip install -e ".[real]"``.
"""

from __future__ import annotations

import json
import time
import urllib.parse
import urllib.request
from collections.abc import Iterator
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from .spectrogram import DEFAULT_CONFIG

__all__ = [
    "DEFAULT_QUERY",
    "RealCorpus",
    "TrackRecord",
    "build_manifest",
    "decode_track",
    "ensure_corpus",
    "load_corpus",
    "load_manifest",
    "write_data_sources",
]

#: Search that returns only CC-licensed music audio with a variable-bitrate MP3.
#: ``licenseurl:(*creativecommons*)`` guarantees every hit is attributable.
DEFAULT_QUERY = (
    "collection:netlabels AND mediatype:audio "
    "AND format:(VBR MP3) AND licenseurl:(*creativecommons*)"
)

_ADVSEARCH = "https://archive.org/advancedsearch.php"
_METADATA = "https://archive.org/metadata/{identifier}"
_DOWNLOAD = "https://archive.org/download/{identifier}/{filename}"

_USER_AGENT = "audio-fingerprint-research/0.1 (github.com/saurabhsingh3012/audio-fingerprint)"

#: Working sample rate; matched to the fingerprint pipeline so no config juggling
#: is needed downstream. librosa resamples on decode.
SAMPLE_RATE = DEFAULT_CONFIG.sample_rate

_last_request_at = 0.0


def _polite_sleep(min_interval_s: float) -> None:
    """Sleep so consecutive network calls are at least ``min_interval_s`` apart.

    The Internet Archive asks automated clients to rate-limit; this keeps the
    whole download well under one request per second on average.
    """
    global _last_request_at
    now = time.monotonic()
    wait = min_interval_s - (now - _last_request_at)
    if wait > 0:
        time.sleep(wait)
    _last_request_at = time.monotonic()


def _http_get(url: str, *, rate_limit_s: float, retries: int = 3, timeout: float = 45.0) -> bytes:
    """GET ``url`` with a user agent, rate limiting, and bounded retries."""
    last_err: Exception | None = None
    for attempt in range(retries):
        _polite_sleep(rate_limit_s)
        try:
            req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
            with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310 - https only
                return resp.read()
        except Exception as err:  # noqa: BLE001 - network is flaky; retry then give up
            last_err = err
            time.sleep(1.0 + attempt)
    raise RuntimeError(f"GET failed after {retries} attempts: {url}\n  last error: {last_err}")


def _get_json(url: str, *, rate_limit_s: float) -> dict:
    """GET and parse a JSON document."""
    return json.loads(_http_get(url, rate_limit_s=rate_limit_s).decode("utf-8"))


@dataclass(frozen=True)
class TrackRecord:
    """Provenance and location of one REAL track.

    Attributes:
        track_id: Stable identifier used by the index and evaluation.
        name: Display name (``"creator — title"``), also what the index stores.
        role: ``"reference"`` (indexed) or ``"impostor"`` (held out of the index,
            used only to measure the false-accept rate).
        identifier: Internet Archive item identifier.
        filename: MP3 file name within the item.
        title: Track title from the item metadata.
        creator: Artist / creator string.
        license: Full Creative-Commons license URL. Never empty by construction.
        length_s: Track duration in seconds, as reported by Archive.org.
        bytes: File size on disk.
        rel_path: Path to the cached audio, relative to the data directory.
    """

    track_id: int
    name: str
    role: str
    identifier: str
    filename: str
    title: str
    creator: str
    license: str
    length_s: float
    bytes: int
    rel_path: str


@dataclass
class RealCorpus:
    """A decoded REAL corpus, duck-compatible with :class:`synth.Corpus`.

    Exposes ``specs`` (each with ``track_id`` and ``name``) and an ``audio`` dict
    keyed by ``track_id``, so the existing evaluation helpers accept it unchanged.
    """

    specs: list[TrackRecord]
    audio: dict[int, NDArray[np.float64]] = field(default_factory=dict)
    sample_rate: int = SAMPLE_RATE

    def __len__(self) -> int:
        return len(self.specs)

    def with_role(self, role: str) -> RealCorpus:
        """A view containing only tracks with the given ``role``."""
        specs = [s for s in self.specs if s.role == role]
        return RealCorpus(
            specs=specs,
            audio={s.track_id: self.audio[s.track_id] for s in specs if s.track_id in self.audio},
            sample_rate=self.sample_rate,
        )


# --------------------------------------------------------------------------
# Selection
# --------------------------------------------------------------------------


def _iter_identifiers(
    query: str, *, rate_limit_s: float, page_size: int = 100, max_pages: int = 40
) -> Iterator[str]:
    """Yield item identifiers for ``query``, paged and stably sorted.

    Sorting by ``identifier`` makes the scan order deterministic, so the same
    filters select the same tracks on every run (network permitting) — which is
    what lets the manifest be a faithful, reproducible description of the corpus.
    """
    for page in range(1, max_pages + 1):
        params = {
            "q": query,
            "fl[]": "identifier",
            "rows": str(page_size),
            "page": str(page),
            "sort[]": "identifier asc",
            "output": "json",
        }
        url = _ADVSEARCH + "?" + urllib.parse.urlencode(params, doseq=True)
        docs = _get_json(url, rate_limit_s=rate_limit_s)["response"]["docs"]
        if not docs:
            return
        for doc in docs:
            ident = doc.get("identifier")
            if ident:
                yield ident


def _pick_file(
    meta: dict, *, min_s: float, max_s: float, max_bytes: int, target_s: float
) -> dict | None:
    """Choose one suitable MP3 from an item, deterministically.

    Keeps files whose duration is in ``[min_s, max_s]`` and whose size is at most
    ``max_bytes``, then picks the one closest to ``target_s`` (ties broken by
    name). Preferring a mid-length track avoids album intros/interludes and keeps
    per-file size bounded so the whole corpus stays a modest download.
    """
    suitable: list[dict] = []
    for f in meta.get("files", []):
        if f.get("format") != "VBR MP3":
            continue
        if not f.get("name", "").lower().endswith(".mp3"):
            continue
        try:
            length = float(f.get("length", 0.0))
            size = int(f.get("size", 0))
        except (TypeError, ValueError):
            continue
        if min_s <= length <= max_s and 0 < size <= max_bytes:
            suitable.append({"name": f["name"], "length": length, "size": size})
    if not suitable:
        return None
    suitable.sort(key=lambda f: (abs(f["length"] - target_s), f["name"]))
    return suitable[0]


# --------------------------------------------------------------------------
# Decode
# --------------------------------------------------------------------------


def decode_track(
    path: str | Path, *, sample_rate: int = SAMPLE_RATE, normalize_rms: float = 0.1
) -> NDArray[np.float64]:
    """Decode an audio file to a mono float64 array at ``sample_rate``.

    Args:
        path: Audio file on disk.
        sample_rate: Target rate; librosa resamples to it.
        normalize_rms: If > 0, scale the whole track to this RMS. The fingerprint
            is gain-invariant so this does not change matching, but it keeps every
            track at a comparable loudness (matching the synthetic corpus's
            convention) and gives the measured-SNR degradation a stable reference.

    Returns:
        A mono signal. Raises if the file cannot be decoded to non-silent audio.
    """
    import librosa  # lazy: keeps the core package import network/audio-free

    audio, _ = librosa.load(str(path), sr=sample_rate, mono=True)
    audio = np.asarray(audio, dtype=np.float64)
    rms = float(np.sqrt(np.mean(audio**2))) if audio.size else 0.0
    if audio.size == 0 or rms <= 1e-8:
        raise ValueError(f"decoded audio is empty or silent: {path}")
    if normalize_rms > 0:
        audio = audio * (normalize_rms / rms)
    return audio


# --------------------------------------------------------------------------
# Build / load
# --------------------------------------------------------------------------


def build_manifest(
    *,
    n_reference: int,
    n_impostors: int,
    data_dir: str | Path,
    query: str = DEFAULT_QUERY,
    min_seconds: float = 40.0,
    max_seconds: float = 300.0,
    target_seconds: float = 120.0,
    max_bytes: int = 7_000_000,
    rate_limit_s: float = 1.1,
    verbose: bool = True,
) -> dict:
    """Download a REAL corpus and write ``manifest.json`` under ``data_dir``.

    Scans the search results in a deterministic order, takes **one** track per
    item (for artist/album diversity), downloads it, verifies it decodes to
    non-silent audio, and assigns roles: the first ``n_reference`` good tracks are
    indexed, the next ``n_impostors`` are held out to measure false accepts.

    Returns the manifest dict (also written to disk). Idempotent at the file
    level: an already-downloaded audio file is not re-fetched.
    """
    data_dir = Path(data_dir)
    audio_dir = data_dir / "audio"
    audio_dir.mkdir(parents=True, exist_ok=True)
    n_total = n_reference + n_impostors

    records: list[TrackRecord] = []
    seen_items: set[str] = set()
    for ident in _iter_identifiers(query, rate_limit_s=rate_limit_s):
        if len(records) >= n_total:
            break
        if ident in seen_items:
            continue
        seen_items.add(ident)
        try:
            meta = _get_json(_METADATA.format(identifier=ident), rate_limit_s=rate_limit_s)
        except RuntimeError:
            continue
        md = meta.get("metadata", {})
        license_url = md.get("licenseurl", "")
        if "creativecommons" not in license_url:
            continue  # defensive: the query already filters, but never trust it
        chosen = _pick_file(
            meta, min_s=min_seconds, max_s=max_seconds,
            max_bytes=max_bytes, target_s=target_seconds,
        )
        if chosen is None:
            continue

        track_id = len(records)
        safe = f"{ident}__{chosen['name']}".replace("/", "_")
        dest = audio_dir / safe
        if not dest.exists():
            url = _DOWNLOAD.format(
                identifier=ident, filename=urllib.parse.quote(chosen["name"])
            )
            try:
                dest.write_bytes(_http_get(url, rate_limit_s=rate_limit_s, timeout=120.0))
            except RuntimeError:
                continue
        try:
            decode_track(dest)  # validate; discard undecodable/silent files
        except Exception:  # noqa: BLE001 - a bad decode just means skip this track
            dest.unlink(missing_ok=True)
            continue

        creator = md.get("creator", "")
        if isinstance(creator, list):
            creator = creator[0] if creator else ""
        title = md.get("title", ident)
        name = f"{creator} — {title}".strip(" —") or ident
        role = "reference" if track_id < n_reference else "impostor"
        rec = TrackRecord(
            track_id=track_id, name=name[:120], role=role, identifier=ident,
            filename=chosen["name"], title=str(title)[:120], creator=str(creator)[:80],
            license=license_url, length_s=round(float(chosen["length"]), 2),
            bytes=int(chosen["size"]), rel_path=str(dest.relative_to(data_dir)),
        )
        records.append(rec)
        if verbose:
            lic_short = rec.license.split("/licenses/")[-1]
            print(f"  [{track_id:2d}/{n_total}] {role:9s} {lic_short:14s} "
                  f"{rec.length_s:6.1f}s  {rec.name[:52]}")

    if len(records) < n_total:
        print(f"WARNING: only {len(records)}/{n_total} tracks obtained "
              f"(reference target {n_reference}, impostor target {n_impostors})")

    manifest = dict(
        query=query, sample_rate=SAMPLE_RATE, n_reference=n_reference,
        n_impostors=n_impostors, n_obtained=len(records),
        created_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        tracks=[asdict(r) for r in records],
    )
    (data_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    return manifest


def load_manifest(data_dir: str | Path) -> dict | None:
    """Load ``manifest.json`` from ``data_dir``, or ``None`` if absent."""
    path = Path(data_dir) / "manifest.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def load_corpus(manifest: dict, data_dir: str | Path) -> RealCorpus:
    """Decode every track in ``manifest`` into a :class:`RealCorpus`."""
    data_dir = Path(data_dir)
    sr = int(manifest.get("sample_rate", SAMPLE_RATE))
    specs = [TrackRecord(**t) for t in manifest["tracks"]]
    audio: dict[int, NDArray[np.float64]] = {}
    for rec in specs:
        audio[rec.track_id] = decode_track(data_dir / rec.rel_path, sample_rate=sr)
    return RealCorpus(specs=specs, audio=audio, sample_rate=sr)


def ensure_corpus(
    *,
    n_reference: int,
    n_impostors: int,
    data_dir: str | Path,
    allow_download: bool = True,
    **build_kwargs: object,
) -> RealCorpus:
    """Return a decoded :class:`RealCorpus`, building/downloading it if needed.

    If a manifest already covers at least ``n_reference + n_impostors`` tracks and
    every cached file is present, it is loaded without any network access. This is
    what lets the evaluation be re-run offline once the corpus is cached.
    """
    data_dir = Path(data_dir)
    manifest = load_manifest(data_dir)
    need = n_reference + n_impostors
    have = manifest["n_obtained"] if manifest else 0
    files_ok = bool(manifest) and all(
        (data_dir / t["rel_path"]).exists() for t in manifest["tracks"]
    )
    if manifest and have >= need and files_ok:
        return load_corpus(manifest, data_dir)
    if not allow_download:
        raise RuntimeError(
            f"no cached corpus for {need} tracks under {data_dir} and downloads "
            f"are disabled (allow_download=False)"
        )
    manifest = build_manifest(
        n_reference=n_reference, n_impostors=n_impostors, data_dir=data_dir,
        **build_kwargs,  # type: ignore[arg-type]
    )
    return load_corpus(manifest, data_dir)


def write_data_sources(manifest: dict, path: str | Path) -> None:
    """Write a committed, audio-free attribution table for the corpus.

    Lists every track with its title, creator, exact CC license, and Archive.org
    identifier so the corpus is fully attributable from the repository without any
    audio being redistributed.
    """
    tracks = manifest["tracks"]
    lines = [
        "# Data sources — REAL audio corpus",
        "",
        "Every track below is a Creative-Commons-licensed recording from the "
        "Internet Archive [`netlabels`](https://archive.org/details/netlabels) "
        "collection, fetched by "
        "[`src/audio_fingerprint/corpus.py`](src/audio_fingerprint/corpus.py).",
        "",
        "**No audio is redistributed in this repository.** Files are cached locally "
        "under `data/` (git-ignored) and used only for fingerprinting and "
        "evaluation. This table is the attribution required by the CC licenses; "
        "each row links to the original item, which carries the authoritative "
        "license and full credits.",
        "",
        f"- Search query: `{manifest['query']}`",
        f"- Tracks: {manifest['n_obtained']} "
        f"({manifest['n_reference']} reference / indexed, "
        f"{manifest['n_impostors']} impostor / held out)",
        f"- Working sample rate: {manifest['sample_rate']} Hz (mono)",
        f"- Manifest created: {manifest['created_utc']}",
        "",
        "| # | role | title | creator | license | archive.org item | length |",
        "|--:|------|-------|---------|---------|------------------|-------:|",
    ]
    for t in tracks:
        lic = t["license"]
        lic_short = lic.split("/licenses/")[-1].rstrip("/") if "/licenses/" in lic else lic
        url = f"https://archive.org/details/{t['identifier']}"
        title = str(t["title"]).replace("|", "\\|")
        creator = str(t["creator"]).replace("|", "\\|") or "—"
        lines.append(
            f"| {t['track_id']} | {t['role']} | {title} | {creator} | "
            f"[{lic_short}]({lic}) | [`{t['identifier']}`]({url}) | {t['length_s']:.0f}s |"
        )
    lines.append("")
    Path(path).write_text("\n".join(lines))


def _main(argv: list[str] | None = None) -> None:
    """CLI: download the corpus and (re)generate ``DATA_SOURCES.md``."""
    import argparse

    parser = argparse.ArgumentParser(description="Download a REAL CC-licensed music corpus.")
    parser.add_argument("--n-reference", type=int, default=36)
    parser.add_argument("--n-impostors", type=int, default=12)
    parser.add_argument("--data-dir", type=str, default=str(
        Path(__file__).resolve().parents[2] / "data"))
    parser.add_argument("--data-sources-out", type=str, default=str(
        Path(__file__).resolve().parents[2] / "DATA_SOURCES.md"))
    parser.add_argument("--min-seconds", type=float, default=40.0)
    parser.add_argument("--max-seconds", type=float, default=300.0)
    parser.add_argument("--target-seconds", type=float, default=120.0)
    parser.add_argument("--max-bytes", type=int, default=7_000_000)
    parser.add_argument("--rate-limit", type=float, default=1.1)
    args = parser.parse_args(argv)

    print(f"downloading {args.n_reference} reference + {args.n_impostors} impostor "
          f"tracks into {args.data_dir} ...")
    manifest = build_manifest(
        n_reference=args.n_reference, n_impostors=args.n_impostors, data_dir=args.data_dir,
        min_seconds=args.min_seconds, max_seconds=args.max_seconds,
        target_seconds=args.target_seconds, max_bytes=args.max_bytes,
        rate_limit_s=args.rate_limit,
    )
    write_data_sources(manifest, args.data_sources_out)
    print(f"wrote manifest ({manifest['n_obtained']} tracks) and {args.data_sources_out}")


if __name__ == "__main__":
    _main()
